import XCTest
@testable import EngineeringCalculator

final class MaterialPortableFileTests: XCTestCase {
    private func fixture(id: UUID = UUID(), name: String = "Portable Test Material", builtIn: Bool = false) -> EngineeringMaterial {
        EngineeringMaterial(id:id,name:name,category:"Validation",densityKgM3:8123,grade:"TEST-GRADE",thermalConductivityWMK:12.5,specificHeatCapacityJkgK:456,thermalExpansionMicrostrainPerK:11.2,minimumServiceTemperatureC:-40,maximumServiceTemperatureC:300,youngsModulusGPa:205,poissonsRatio:0.29,yieldStrengthMPa:550,ultimateTensileStrengthMPa:720,shearModulusGPa:79,compressiveStrengthMPa:600,electricalResistivityOhmM:1.1e-6,source:"Portable test fixture",notes:"Must survive portable-file round trip.",isBuiltIn:builtIn,unsDesignation:"S00000",standardDesignation:"TEST 123",productForm:"Bar",materialCondition:"Test condition",thermalConductivitySeries:MaterialPropertySeries(referenceValue:10,referenceTemperatureC:20,equation:MaterialPropertyEquation(a:10,b:0.1,c:0.001,d:0,minimumTemperatureC:0,maximumTemperatureC:200,allowsExtrapolation:false,kind:.polynomial),source:"Polynomial fixture",basis:"k(T) = 10 + 0.1T + 0.001T²"),specificHeatCapacitySeries:MaterialPropertySeries(referenceValue:450,referenceTemperatureC:20,equation:MaterialPropertyEquation(minimumTemperatureC:-40,maximumTemperatureC:300,allowsExtrapolation:false,kind:.linearReference,referenceValue:450,referenceTemperatureC:20,slope:0.25),source:"Linear-reference fixture"),youngsModulusSeries:MaterialPropertySeries(referenceValue:205,referenceTemperatureC:20,temperatureTable:[MaterialPropertyPoint(temperatureC:20,value:205),MaterialPropertyPoint(temperatureC:100,value:198),MaterialPropertyPoint(temperatureC:200,value:188)],source:"Table fixture"),electricalResistivitySeries:MaterialPropertySeries(referenceValue:1.0e-6,referenceTemperatureC:20,equation:MaterialPropertyEquation(minimumTemperatureC:-50,maximumTemperatureC:250,allowsExtrapolation:false,kind:.relativeLinear,referenceValue:1.0e-6,referenceTemperatureC:20,temperatureCoefficient:0.004),source:"TCR fixture"))
    }
    func testSingleMaterialRoundTripPreservesCompletePropertyData() throws { let original=fixture();let data=try MaterialPortableCodec.encode(material:original);let decoded=try MaterialPortableCodec.decode(data);XCTAssertEqual(decoded.kind,.material);XCTAssertEqual(decoded.materials.count,1);var expected=original;expected.isBuiltIn=false;XCTAssertEqual(decoded.materials[0],expected) }
    func testLibraryRoundTripPreservesMultipleMaterials() throws { let originals=[fixture(name:"Alpha"),fixture(name:"Beta")];let data=try MaterialPortableCodec.encode(library:originals);let decoded=try MaterialPortableCodec.decode(data);XCTAssertEqual(decoded.kind,.library);XCTAssertEqual(decoded.materials,originals) }
    func testEquationKindsAndTemperatureTableSurviveRoundTrip() throws { let data=try MaterialPortableCodec.encode(material:fixture());let material=try XCTUnwrap(MaterialPortableCodec.decode(data).materials.first);XCTAssertEqual(material.thermalConductivitySeries?.equation?.effectiveKind,.polynomial);XCTAssertEqual(material.specificHeatCapacitySeries?.equation?.effectiveKind,.linearReference);XCTAssertEqual(material.electricalResistivitySeries?.equation?.effectiveKind,.relativeLinear);XCTAssertEqual(material.youngsModulusSeries?.temperatureTable.count,3);XCTAssertEqual(try XCTUnwrap(material.youngsModulusSeries?.value(atTemperatureC:150)),193,accuracy:1e-12);XCTAssertEqual(try XCTUnwrap(material.electricalResistivitySeries?.value(atTemperatureC:120)),1.4e-6,accuracy:1e-15) }
    func testMalformedJSONIsRejected(){XCTAssertThrowsError(try MaterialPortableCodec.decode(Data("not json".utf8))){XCTAssertEqual($0 as? MaterialImportError,.malformedFile)}}
    func testUnsupportedFormatIsRejected() throws {let data=Data("{\"format\":\"OtherFormat\",\"formatVersion\":1,\"materials\":[{\"id\":\"00000000-0000-0000-0000-000000000001\",\"name\":\"X\",\"category\":\"Other\",\"isBuiltIn\":false}]}".utf8);XCTAssertThrowsError(try MaterialPortableCodec.decode(data)){XCTAssertEqual($0 as? MaterialImportError,.unsupportedFormat("OtherFormat"))}}
    func testFutureFormatVersionIsRejected() throws {let encoder=JSONEncoder();let document=MaterialPortableDocument(kind:.library,materials:[fixture()]);var object=try XCTUnwrap(JSONSerialization.jsonObject(with:encoder.encode(document)) as? [String:Any]);object["formatVersion"]=MaterialPortableDocument.currentFormatVersion+1;let data=try JSONSerialization.data(withJSONObject:object);XCTAssertThrowsError(try MaterialPortableCodec.decode(data)){XCTAssertEqual($0 as? MaterialImportError,.unsupportedVersion(MaterialPortableDocument.currentFormatVersion+1))}}
    func testEmptyLibraryIsRejected() throws {let data=try JSONEncoder().encode(MaterialPortableDocument(kind:.library,materials:[]));XCTAssertThrowsError(try MaterialPortableCodec.decode(data)){XCTAssertEqual($0 as? MaterialImportError,.emptyLibrary)}}
    func testSingleMaterialDocumentRejectsMultipleMaterials() throws {let data=try JSONEncoder().encode(MaterialPortableDocument(kind:.material,materials:[fixture(name:"A"),fixture(name:"B")]));XCTAssertThrowsError(try MaterialPortableCodec.decode(data)){XCTAssertEqual($0 as? MaterialImportError,.invalidMaterialCount(2))}}
    func testMergeRegeneratesDuplicateUUID(){let id=UUID();let merged=MaterialPortableCodec.merge(imported:[fixture(id:id,name:"Incoming")],into:[fixture(id:id,name:"Existing")]);XCTAssertEqual(merged.materials.count,2);XCTAssertEqual(merged.materials[0].id,id);XCTAssertNotEqual(merged.materials[1].id,id);XCTAssertEqual(merged.report.regeneratedUUIDCount,1);XCTAssertEqual(merged.report.importedCount,1)}
    func testMergeRenamesDuplicateNamesCaseInsensitively(){let merged=MaterialPortableCodec.merge(imported:[fixture(name:"duplex steel")],into:[fixture(name:"Duplex Steel")]);XCTAssertEqual(merged.materials[1].name,"duplex steel (Imported 2)");XCTAssertEqual(merged.report.renamedCount,1)}
    func testMergeUsesNextAvailableImportedSuffix(){let existing=[fixture(name:"Steel"),fixture(name:"Steel (Imported 2)"),fixture(name:"Steel (Imported 3)")];let merged=MaterialPortableCodec.merge(imported:[fixture(name:"Steel")],into:existing);XCTAssertEqual(merged.materials.last?.name,"Steel (Imported 4)")}
    func testBuiltInFlagIsRemovedOnExportAndImport() throws {let builtIn=fixture(name:"Built In Source",builtIn:true);let decoded=try XCTUnwrap(MaterialPortableCodec.decode(MaterialPortableCodec.encode(material:builtIn)).materials.first);XCTAssertFalse(decoded.isBuiltIn);XCTAssertFalse(try XCTUnwrap(MaterialPortableCodec.merge(imported:[builtIn],into:[]).materials.first).isBuiltIn)}
}

final class MaterialRequirementValidatorTests: XCTestCase {
    func testCompleteTransientThermalMaterialPasses(){let r=MaterialRequirementValidator.validate(material:V.complete,against:StandardMaterialRequirementSets.transientThermal,calculationTemperatureC:50);XCTAssertTrue(r.canCalculate);XCTAssertTrue(r.issues.isEmpty)}
    func testMissingDensityBlocksCalculation(){let r=MaterialRequirementValidator.validate(material:V.missingDensity,against:StandardMaterialRequirementSets.transientThermal,calculationTemperatureC:50);XCTAssertFalse(r.canCalculate);XCTAssertEqual(r.errors.map(\.property),[.density])}
    func testMissingConductivityBlocksCalculation(){let r=MaterialRequirementValidator.validate(material:V.missingK,against:StandardMaterialRequirementSets.transientThermal,calculationTemperatureC:50);XCTAssertEqual(r.errors.map(\.property),[.thermalConductivity])}
    func testMissingHeatCapacityBlocksCalculation(){let r=MaterialRequirementValidator.validate(material:V.missingCp,against:StandardMaterialRequirementSets.transientThermal,calculationTemperatureC:50);XCTAssertEqual(r.errors.map(\.property),[.specificHeatCapacity])}
    func testMultipleMissingPropertiesReportedTogether(){let r=MaterialRequirementValidator.validate(material:V.empty,against:StandardMaterialRequirementSets.transientThermal,calculationTemperatureC:50);XCTAssertEqual(Set(r.errors.map(\.property)),Set([.density,.specificHeatCapacity,.thermalConductivity]));XCTAssertEqual(r.errors.count,3)}
    func testTemperatureRequiredIsReported(){let r=MaterialRequirementValidator.validate(material:V.tabulatedK,against:StandardMaterialRequirementSets.steadyStateConduction);XCTAssertEqual(r.errors.first?.reason,.temperatureRequired)}
    func testTableInsideRangePasses(){XCTAssertTrue(MaterialRequirementValidator.validate(material:V.tabulatedK,against:StandardMaterialRequirementSets.steadyStateConduction,calculationTemperatureC:50).canCalculate)}
    func testTableOutsideRangeBlocks(){let r=MaterialRequirementValidator.validate(material:V.tabulatedK,against:StandardMaterialRequirementSets.steadyStateConduction,calculationTemperatureC:150);XCTAssertEqual(r.errors.first?.reason,.outsideAvailableRange(minimumC:0,maximumC:100))}
    func testEquationInsideRangePasses(){XCTAssertTrue(MaterialRequirementValidator.validate(material:V.equationK,against:StandardMaterialRequirementSets.steadyStateConduction,calculationTemperatureC:80).canCalculate)}
    func testEquationOutsideRangeBlocks(){let r=MaterialRequirementValidator.validate(material:V.equationK,against:StandardMaterialRequirementSets.steadyStateConduction,calculationTemperatureC:150);XCTAssertEqual(r.errors.first?.reason,.outsideEquationRange(minimumC:0,maximumC:100))}
    func testExtrapolationAllowedPasses(){XCTAssertTrue(MaterialRequirementValidator.validate(material:V.extrapolatingK,against:StandardMaterialRequirementSets.steadyStateConduction,calculationTemperatureC:150).canCalculate)}
    func testOptionalMissingPropertyWarnsButDoesNotBlock(){let set=MaterialRequirementSet(id:"optional",name:"Optional",requirements:[.init(.density),.init(.youngsModulus,level:.optional)]);let r=MaterialRequirementValidator.validate(material:V.densityOnly,against:set);XCTAssertTrue(r.canCalculate);XCTAssertEqual(r.warnings.first?.property,.youngsModulus)}
    func testOnlyInvalidMaterialIsNamed(){let r=MaterialRequirementValidator.validate(materials:[V.complete,V.missingDensity],against:StandardMaterialRequirementSets.transientThermal,calculationTemperatureC:50);XCTAssertEqual(r.errors.count,1);XCTAssertEqual(r.errors.first?.materialName,"Test - Missing Density")}
    func testLinearElasticRequirements(){XCTAssertTrue(MaterialRequirementValidator.validate(material:V.complete,against:StandardMaterialRequirementSets.linearElastic).canCalculate);let bad=MaterialRequirementValidator.validate(material:V.densityOnly,against:StandardMaterialRequirementSets.linearElastic);XCTAssertEqual(Set(bad.errors.map(\.property)),Set([.youngsModulus,.poissonsRatio]))}
}

private enum V {
    static let complete=EngineeringMaterial(name:"Test - Complete",densityKgM3:1000,thermalConductivityWMK:10,specificHeatCapacityJkgK:1000,youngsModulusGPa:100,poissonsRatio:0.3)
    static let densityOnly=EngineeringMaterial(name:"Test - Density Only",densityKgM3:1000)
    static let missingDensity=EngineeringMaterial(name:"Test - Missing Density",thermalConductivityWMK:10,specificHeatCapacityJkgK:1000)
    static let missingK=EngineeringMaterial(name:"Test - Missing Conductivity",densityKgM3:1000,specificHeatCapacityJkgK:1000)
    static let missingCp=EngineeringMaterial(name:"Test - Missing Heat Capacity",densityKgM3:1000,thermalConductivityWMK:10)
    static let empty=EngineeringMaterial(name:"Test - Empty")
    static let tabulatedK=EngineeringMaterial(name:"Test - Tabulated K",thermalConductivitySeries:MaterialPropertySeries(temperatureTable:[.init(temperatureC:0,value:10),.init(temperatureC:100,value:20)]))
    static let equationK=EngineeringMaterial(name:"Test - Equation K",thermalConductivitySeries:MaterialPropertySeries(equation:MaterialPropertyEquation(a:10,b:0.1,minimumTemperatureC:0,maximumTemperatureC:100,allowsExtrapolation:false)))
    static let extrapolatingK=EngineeringMaterial(name:"Test - Extrapolating K",thermalConductivitySeries:MaterialPropertySeries(equation:MaterialPropertyEquation(a:10,b:0.1,minimumTemperatureC:0,maximumTemperatureC:100,allowsExtrapolation:true)))
}
