import XCTest
@testable import EngineeringCalculator

final class PipeHeatTransferCalculatorTests: XCTestCase {
    private let k10=EngineeringMaterial(name:"TEST k=10",category:"Validation",thermalConductivityWMK:10)
    private let k20=EngineeringMaterial(name:"TEST k=20",category:"Validation",thermalConductivityWMK:20)
    private let densityOnly=EngineeringMaterial(name:"TEST Missing k",category:"Validation",densityKgM3:1000)
    private var tabulated:EngineeringMaterial{EngineeringMaterial(name:"TEST Table k",category:"Validation",thermalConductivitySeries:MaterialPropertySeries(temperatureTable:[.init(temperatureC:0,value:10),.init(temperatureC:50,value:15),.init(temperatureC:100,value:20)]))}
    private var steep:EngineeringMaterial{EngineeringMaterial(name:"TEST Steep k(T)",category:"Validation",thermalConductivitySeries:MaterialPropertySeries(temperatureTable:[.init(temperatureC:0,value:1),.init(temperatureC:100,value:5)]))}
    private func input(layers:[PipeHeatTransferLayer],inside:Double=100,outside:Double=0,length:Double=1)->PipeHeatTransferInput{.init(internalDiameterM:0.300,layers:layers,insideBoundaryTemperatureC:inside,outsideBoundaryTemperatureC:outside,lengthM:length)}

    func testSingleLayerConstantKMatchesAnalyticalResistance() throws {let result=try XCTUnwrap(PipeHeatTransferCalculator.validatedCalculate(input:input(layers:[.init(thicknessM:0.020,material:k10)])).result);let r=log(0.170/0.150)/(2*Double.pi*10);XCTAssertEqual(result.totalResistanceKPerW,r,accuracy:1e-12);XCTAssertEqual(result.heatRateW,100/r,accuracy:1e-8);XCTAssertEqual(result.finalOuterDiameterM,0.340,accuracy:1e-12);XCTAssertEqual(result.totalComputationalCells,1)}
    func testTwoLayerResistanceIsSumOfCylindricalResistances() throws {let result=try XCTUnwrap(PipeHeatTransferCalculator.validatedCalculate(input:input(layers:[.init(thicknessM:0.010,material:k10),.init(thicknessM:0.020,material:k20)])).result);let r1=log(0.160/0.150)/(2*Double.pi*10),r2=log(0.180/0.160)/(2*Double.pi*20);XCTAssertEqual(result.totalResistanceKPerW,r1+r2,accuracy:1e-12);XCTAssertEqual(result.heatRateW,100/(r1+r2),accuracy:1e-8)}
    func testMissingConductivityBlocksCalculation(){let v=PipeHeatTransferCalculator.validatedCalculate(input:input(layers:[.init(name:"Insulation",thicknessM:0.020,material:densityOnly)]));XCTAssertFalse(v.canCalculate);XCTAssertNil(v.result);XCTAssertEqual(v.validation.errors.first?.property,.thermalConductivity);XCTAssertEqual(v.validation.layers.first?.layerName,"Insulation")}
    func testDensityIsNotRequiredForHeatConduction(){XCTAssertTrue(PipeHeatTransferCalculator.validatedCalculate(input:input(layers:[.init(thicknessM:0.020,material:k10)])).canCalculate)}

    func testTemperatureDependentSingleLayerUsesAdaptiveCells() throws {let r=try XCTUnwrap(PipeHeatTransferCalculator.validatedCalculate(input:input(layers:[.init(thicknessM:0.100,material:steep)])).result);XCTAssertGreaterThan(r.layers[0].computationalCellCount,1);XCTAssertGreaterThan(r.layers[0].maximumConductivityWMK,r.layers[0].minimumConductivityWMK);XCTAssertEqual(r.layers[0].innerBoundaryTemperatureC,100,accuracy:1e-7);XCTAssertEqual(r.layers[0].outerBoundaryTemperatureC,0,accuracy:1e-7)}
    func testLinearKSingleLayerMatchesConductivityIntegral(){let model=input(layers:[.init(thicknessM:0.100,material:steep)]);let v=PipeHeatTransferCalculator.validatedCalculate(input:model);guard let r=v.result else{return XCTFail("Expected adaptive result")};let integralK=300.0 // integral_0^100 (1+0.04T)dT
        let expected=2*Double.pi*model.lengthM*integralK/log(0.250/0.150);XCTAssertEqual(r.heatRateW,expected,accuracy:expected*0.003)}
    func testConstantKThickLayerDoesNotNeedSubdivision() throws {let r=try XCTUnwrap(PipeHeatTransferCalculator.validatedCalculate(input:input(layers:[.init(thicknessM:0.500,material:k10)])).result);XCTAssertEqual(r.layers[0].computationalCellCount,1)}
    func testAdaptiveLayerTemperaturesRemainContinuous() throws {let r=try XCTUnwrap(PipeHeatTransferCalculator.validatedCalculate(input:input(layers:[.init(thicknessM:0.020,material:k10),.init(thicknessM:0.100,material:steep)])).result);XCTAssertEqual(r.layers[0].outerBoundaryTemperatureC,r.layers[1].innerBoundaryTemperatureC,accuracy:1e-7);XCTAssertEqual(r.layers.reduce(0){$0+$1.temperatureDropC},100,accuracy:1e-6)}
    func testAdaptiveSolverReportsConvergenceMetadata() throws {let r=try XCTUnwrap(PipeHeatTransferCalculator.validatedCalculate(input:input(layers:[.init(thicknessM:0.100,material:steep)])).result);XCTAssertGreaterThanOrEqual(r.refinementPasses,1);XCTAssertGreaterThanOrEqual(r.totalComputationalCells,1);XCTAssertGreaterThanOrEqual(r.heatRateConvergenceFraction,0)}
    func testOutOfRangeAtBoundaryBlocksAdaptiveCalculation(){let v=PipeHeatTransferCalculator.validatedCalculate(input:input(layers:[.init(thicknessM:0.020,material:tabulated)],inside:120,outside:20));XCTAssertFalse(v.canCalculate);XCTAssertNil(v.result)}

    func testTabulatedConductivityAtUniformMeanCase() throws {let result=try XCTUnwrap(PipeHeatTransferCalculator.validatedCalculate(input:input(layers:[.init(thicknessM:0.020,material:tabulated)],inside:100,outside:0)).result);XCTAssertGreaterThan(result.layers[0].thermalConductivityWMK,10);XCTAssertLessThan(result.layers[0].thermalConductivityWMK,20)}
    func testLayerTemperatureDropsSumToSpecifiedBoundaryDifference() throws {let result=try XCTUnwrap(PipeHeatTransferCalculator.validatedCalculate(input:input(layers:[.init(thicknessM:0.010,material:k10),.init(thicknessM:0.020,material:k20)],inside:120,outside:20)).result);XCTAssertEqual(result.layers.reduce(0){$0+$1.temperatureDropC},100,accuracy:1e-8);XCTAssertEqual(result.layers.last?.outerBoundaryTemperatureC ?? .nan,20,accuracy:1e-8)}
    func testHeatRateScalesWithLengthButHeatRatePerLengthDoesNot() throws {let one=try XCTUnwrap(PipeHeatTransferCalculator.validatedCalculate(input:input(layers:[.init(thicknessM:0.020,material:k10)],length:1)).result);let five=try XCTUnwrap(PipeHeatTransferCalculator.validatedCalculate(input:input(layers:[.init(thicknessM:0.020,material:k10)],length:5)).result);XCTAssertEqual(five.heatRateW,one.heatRateW*5,accuracy:1e-7);XCTAssertEqual(five.heatRatePerLengthWM,one.heatRatePerLengthWM,accuracy:1e-7)}
}
