import XCTest
@testable import EngineeringCalculator

final class PipeHeatTransferPersistenceTests: XCTestCase {
    private let constantID=UUID(uuidString:"C1000000-0000-0000-0000-000000000001")!
    private let variableID=UUID(uuidString:"C1000000-0000-0000-0000-000000000002")!
    private func constant()->EngineeringMaterial{.init(id:constantID,name:"Regression Constant k",category:"Validation",thermalConductivityWMK:10,source:"Heat-transfer regression fixture")}
    private func variable()->EngineeringMaterial{.init(id:variableID,name:"Regression k(T)",category:"Validation",source:"Heat-transfer regression fixture",thermalConductivitySeries:.init(temperatureTable:[.init(temperatureC:0,value:1),.init(temperatureC:50,value:3),.init(temperatureC:100,value:5)]))}
    private func model()->PipeHeatTransferInput{.init(internalDiameterM:0.300,layers:[.init(id:UUID(uuidString:"C2000000-0000-0000-0000-000000000001")!,name:"Steel",thicknessM:0.020,material:constant()),.init(id:UUID(uuidString:"C2000000-0000-0000-0000-000000000002")!,name:"Temperature dependent insulation",thicknessM:0.080,material:variable())],insideBoundaryTemperatureC:100,outsideBoundaryTemperatureC:0,lengthM:1)}
    private func solved(_ input:PipeHeatTransferInput)throws->PipeHeatTransferResult{try XCTUnwrap(PipeHeatTransferCalculator.validatedCalculate(input:input).result)}

    func testCreatesStandaloneDocumentEmbeddingOnlyUsedMaterials() throws {let m=model(),r=try solved(m),d=try PipeHeatTransferPersistence.makeDocument(name:"Heat Baseline",input:m,result:r,createdAt:Date(timeIntervalSince1970:1_700_000_000));XCTAssertEqual(d.kind,.standaloneCalculation);XCTAssertEqual(d.calculations[0].calculatorID,PipeHeatTransferPersistence.calculatorID);XCTAssertEqual(Set(d.embeddedMaterials.map(\.id)),Set([constantID,variableID]));XCTAssertEqual(d.embeddedMaterials.count,2)}
    func testRestoreReconstructsExactInputsAndMaterialSnapshots() throws {let m=model(),d=try PipeHeatTransferPersistence.makeDocument(name:"Heat",input:m,result:try solved(m));let restored=try PipeHeatTransferPersistence.restore(from:d);XCTAssertEqual(restored.input,m);XCTAssertEqual(restored.input.layers[1].material.thermalConductivitySeries,m.layers[1].material.thermalConductivitySeries)}
    func testFileRoundTripRecalculatesTemperatureDependentCase() throws {let m=model(),r=try solved(m),date=Date(timeIntervalSince1970:1_700_000_000),d=try PipeHeatTransferPersistence.makeDocument(name:"Heat Build Baseline",input:m,result:r,createdAt:date),data=try CalculationDocumentFileIO.data(for:d),decoded=try CalculationDocumentFileIO.document(from:data),restored=try PipeHeatTransferPersistence.restore(from:decoded),rerun=try solved(restored.input);XCTAssertTrue(PipeHeatTransferPersistence.compareStoredOutputs(restored.storedOutputs,with:rerun).isEmpty);XCTAssertEqual(rerun.heatRateW,r.heatRateW,accuracy:1e-9);XCTAssertEqual(rerun.totalComputationalCells,r.totalComputationalCells)}
    func testChangedBoundaryTemperatureIsDetectedAgainstBaseline() throws {let m=model(),d=try PipeHeatTransferPersistence.makeDocument(name:"Baseline",input:m,result:try solved(m));let restored=try PipeHeatTransferPersistence.restore(from:d);var changed=restored.input;changed.insideBoundaryTemperatureC=90;let rerun=try solved(changed),diff=PipeHeatTransferPersistence.compareStoredOutputs(restored.storedOutputs,with:rerun);XCTAssertFalse(diff.isEmpty);XCTAssertTrue(diff.contains(.init(rawValue:"heatRateW")))}
    func testAdaptiveSolverMetadataIsPartOfRegressionBaseline() throws {let m=model(),r=try solved(m);XCTAssertGreaterThan(r.totalComputationalCells,2);let d=try PipeHeatTransferPersistence.makeDocument(name:"Adaptive",input:m,result:r);let stored=d.calculations[0].outputs;XCTAssertTrue(stored.contains(where:{$0.id.rawValue=="totalComputationalCells"}));XCTAssertTrue(stored.contains(where:{$0.id.rawValue=="refinementPasses"}));XCTAssertTrue(stored.contains(where:{$0.id.rawValue=="layer.1.computationalCellCount"}))}
    func testSameMaterialOnMultipleLayersEmbedsOneSnapshot() throws {let material=constant();let m=PipeHeatTransferInput(internalDiameterM:0.3,layers:[.init(thicknessM:0.01,material:material),.init(thicknessM:0.02,material:material)],insideBoundaryTemperatureC:100,outsideBoundaryTemperatureC:0);let d=try PipeHeatTransferPersistence.makeDocument(name:"Shared",input:m,result:try solved(m));XCTAssertEqual(d.embeddedMaterials.count,1);XCTAssertEqual(d.embeddedMaterials[0].id,constantID)}
}
