import SwiftUI

enum MaterialPropertyInputMode: String, CaseIterable, Identifiable { case constant="Constant", table="Table", equation="Equation"; var id:Self{self} }
struct EditableMaterialPropertyPoint: Identifiable, Hashable { var id=UUID(); var temperatureC:String=""; var value:String="" }
struct MaterialPropertyDraftResult { let fallback: Double?; let series: MaterialPropertySeries? }

struct MaterialPropertyDraft: Hashable {
    var mode:MaterialPropertyInputMode; var constantValue:String; var referenceTemperatureC:String; var table:[EditableMaterialPropertyPoint]
    var equationKind:MaterialEquationKind; var a:String; var b:String; var c:String; var d:String; var slope:String; var temperatureCoefficient:String
    var minimumTemperatureC:String; var maximumTemperatureC:String; var allowsExtrapolation:Bool; var source:String; var basis:String
    init(fallback:Double?,series:MaterialPropertySeries?){
        constantValue=EngineeringNumberFormatter.editableString(series?.referenceValue ?? fallback); referenceTemperatureC=EngineeringNumberFormatter.editableString(series?.referenceTemperatureC)
        table=(series?.temperatureTable ?? []).sorted{$0.temperatureC<$1.temperatureC}.map{EditableMaterialPropertyPoint(temperatureC:EngineeringNumberFormatter.editableString($0.temperatureC),value:EngineeringNumberFormatter.editableString($0.value))}
        if let e=series?.equation { mode = .equation; equationKind=e.effectiveKind; a=EngineeringNumberFormatter.editableString(e.a); b=EngineeringNumberFormatter.editableString(e.b); c=EngineeringNumberFormatter.editableString(e.c); d=EngineeringNumberFormatter.editableString(e.d); slope=EngineeringNumberFormatter.editableString(e.slope); temperatureCoefficient=EngineeringNumberFormatter.editableString(e.temperatureCoefficient); if e.effectiveKind != .polynomial { constantValue=EngineeringNumberFormatter.editableString(e.referenceValue); referenceTemperatureC=EngineeringNumberFormatter.editableString(e.referenceTemperatureC) }; minimumTemperatureC=EngineeringNumberFormatter.editableString(e.minimumTemperatureC); maximumTemperatureC=EngineeringNumberFormatter.editableString(e.maximumTemperatureC); allowsExtrapolation=e.allowsExtrapolation }
        else { mode = table.isEmpty ? .constant : .table; equationKind = .polynomial; a = "0"; b = "0"; c = "0"; d = "0"; slope = "0"; temperatureCoefficient = "0"; minimumTemperatureC = ""; maximumTemperatureC = ""; allowsExtrapolation = false }
        source=series?.source ?? ""; basis=series?.basis ?? ""
    }
    private func number(_ s:String)->Double?{EngineeringNumberFormatter.parse(s)}
    var scalarValue:Double?{number(constantValue)}
    func makeSeries()->MaterialPropertyDraftResult{
        let fallback = number(constantValue)
        switch mode {
        case .constant:return MaterialPropertyDraftResult(fallback:fallback,series:nil)
        case .table:
            let points=table.compactMap{row->MaterialPropertyPoint? in guard let t=number(row.temperatureC),let v=number(row.value) else{return nil};return MaterialPropertyPoint(temperatureC:t,value:v)}.sorted{$0.temperatureC<$1.temperatureC}; guard !points.isEmpty else{return MaterialPropertyDraftResult(fallback:fallback,series:nil)}; let series=MaterialPropertySeries(referenceValue:fallback,referenceTemperatureC:number(referenceTemperatureC),temperatureTable:points,source:source.isEmpty ? nil:source,basis:basis.isEmpty ? nil:basis); return MaterialPropertyDraftResult(fallback:fallback,series:series)
        case .equation:
            let e:MaterialPropertyEquation
            switch equationKind {
            case .polynomial: guard let aa=number(a),let bb=number(b),let cc=number(c),let dd=number(d) else{return MaterialPropertyDraftResult(fallback:fallback,series:nil)}; e=MaterialPropertyEquation(a:aa,b:bb,c:cc,d:dd,minimumTemperatureC:number(minimumTemperatureC),maximumTemperatureC:number(maximumTemperatureC),allowsExtrapolation:allowsExtrapolation,kind:.polynomial)
            case .linearReference: guard let y0=fallback,let t0=number(referenceTemperatureC),let k=number(slope) else{return MaterialPropertyDraftResult(fallback:fallback,series:nil)}; e=MaterialPropertyEquation(minimumTemperatureC:number(minimumTemperatureC),maximumTemperatureC:number(maximumTemperatureC),allowsExtrapolation:allowsExtrapolation,kind:.linearReference,referenceValue:y0,referenceTemperatureC:t0,slope:k)
            case .relativeLinear: guard let y0=fallback,let t0=number(referenceTemperatureC),let alpha=number(temperatureCoefficient) else{return MaterialPropertyDraftResult(fallback:fallback,series:nil)}; e=MaterialPropertyEquation(minimumTemperatureC:number(minimumTemperatureC),maximumTemperatureC:number(maximumTemperatureC),allowsExtrapolation:allowsExtrapolation,kind:.relativeLinear,referenceValue:y0,referenceTemperatureC:t0,temperatureCoefficient:alpha)
            }
            let series=MaterialPropertySeries(referenceValue:fallback,referenceTemperatureC:number(referenceTemperatureC),equation:e,source:source.isEmpty ? nil:source,basis:basis.isEmpty ? nil:basis); return MaterialPropertyDraftResult(fallback:fallback,series:series)
        }
    }
}

struct MaterialTemperaturePropertyEditor:View{
    let title:String;let unit:String;@Binding var draft:MaterialPropertyDraft
    var body:some View{VStack(alignment:.leading,spacing:12){ViewThatFits(in:.horizontal){HStack{Text(title).fontWeight(.semibold).fixedSize(horizontal:false,vertical:true);Spacer(minLength:12);modePicker.frame(maxWidth:320)};VStack(alignment:.leading,spacing:8){Text(title).fontWeight(.semibold);modePicker}};switch draft.mode{case .constant:constantEditor;case .table:tableEditor;case .equation:equationEditor}}.padding(.vertical,6)}
    private var modePicker:some View{Picker("Data type",selection:$draft.mode){ForEach(MaterialPropertyInputMode.allCases){Text($0.rawValue).tag($0)}}.labelsHidden().pickerStyle(.segmented)}
    private var constantEditor:some View{HStack{Text("Value").foregroundStyle(.secondary);Spacer();TextField("Value",text:$draft.constantValue).multilineTextAlignment(.trailing).frame(maxWidth:140);if !unit.isEmpty{Text(unit).foregroundStyle(.secondary).fixedSize()}}}
    private var tableEditor:some View{VStack(alignment:.leading,spacing:8){referenceEditor;HStack{Text("Temperature (°C)").font(.caption).foregroundStyle(.secondary).frame(maxWidth:.infinity,alignment:.leading);Text("Value (\(unit))").font(.caption).foregroundStyle(.secondary).frame(maxWidth:.infinity,alignment:.leading);Color.clear.frame(width:30,height:1)};ForEach($draft.table){$row in HStack{TextField("Temperature",text:$row.temperatureC).frame(maxWidth:.infinity);TextField("Value",text:$row.value).frame(maxWidth:.infinity);Button(role:.destructive){draft.table.removeAll{$0.id==row.id}}label:{Image(systemName:"minus.circle")}.buttonStyle(.borderless).frame(width:30)}};Button{draft.table.append(EditableMaterialPropertyPoint())}label:{Label("Add Row",systemImage:"plus")};Text("Linear interpolation is used between table points. Extrapolation beyond the table range is not permitted.").font(.caption).foregroundStyle(.secondary);traceabilityEditor}}
    private var equationEditor:some View{VStack(alignment:.leading,spacing:12){Picker("Equation type",selection:$draft.equationKind){ForEach(MaterialEquationKind.allCases){Text($0.rawValue).tag($0)}};Text(draft.equationKind.formula+"   where T is in °C").font(.callout).monospaced().fixedSize(horizontal:false,vertical:true);switch draft.equationKind{case .polynomial:VStack(spacing:8){parameterRow("Coefficient",symbol:"a",value:$draft.a);parameterRow("Coefficient",symbol:"b",value:$draft.b);parameterRow("Coefficient",symbol:"c",value:$draft.c);parameterRow("Coefficient",symbol:"d",value:$draft.d)};case .linearReference:referenceEquationEditor;parameterRow("Slope",symbol:"k",value:$draft.slope);case .relativeLinear:referenceEquationEditor;parameterRow("Temperature coefficient",symbol:"α",value:$draft.temperatureCoefficient,unit:"K⁻¹")};temperatureRangeEditor;Toggle("Allow extrapolation outside valid range",isOn:$draft.allowsExtrapolation);traceabilityEditor}}
    private var referenceEditor:some View{ViewThatFits(in:.horizontal){HStack{TextField("Reference value",text:$draft.constantValue);if !unit.isEmpty{Text(unit).foregroundStyle(.secondary).fixedSize()};Text("at").foregroundStyle(.secondary);TextField("Reference temperature",text:$draft.referenceTemperatureC).frame(maxWidth:120);Text("°C").foregroundStyle(.secondary)};VStack(alignment:.leading,spacing:8){parameterRow("Reference value",symbol:"y₀",value:$draft.constantValue,unit:unit);parameterRow("Reference temperature",symbol:"T₀",value:$draft.referenceTemperatureC,unit:"°C")}}}
    private var referenceEquationEditor:some View{VStack(spacing:8){parameterRow("Reference value",symbol:"y₀",value:$draft.constantValue,unit:unit);parameterRow("Reference temperature",symbol:"T₀",value:$draft.referenceTemperatureC,unit:"°C")}}
    private var temperatureRangeEditor:some View{VStack(spacing:8){parameterRow("Minimum temperature",symbol:"Tmin",value:$draft.minimumTemperatureC,unit:"°C",symbolFirst:true);parameterRow("Maximum temperature",symbol:"Tmax",value:$draft.maximumTemperatureC,unit:"°C",symbolFirst:true)}}
    private var traceabilityEditor:some View{VStack(alignment:.leading,spacing:12){traceabilityField("Property source",text:$draft.source,prompt:"Source or reference");traceabilityField("Basis / correlation notes",text:$draft.basis,prompt:"Basis, assumptions or correlation notes")}}
    @ViewBuilder private func traceabilityField(_ label:String,text:Binding<String>,prompt:String)->some View{ViewThatFits(in:.horizontal){HStack(alignment:.top,spacing:12){Text(label).foregroundStyle(.secondary).frame(minWidth:150,alignment:.leading);TextField(prompt,text:text,axis:.vertical).multilineTextAlignment(.trailing).lineLimit(1...4)};VStack(alignment:.leading,spacing:5){Text(label).foregroundStyle(.secondary).font(.caption);TextField(prompt,text:text,axis:.vertical).lineLimit(2...5).textFieldStyle(.roundedBorder)}}}
    @ViewBuilder private func parameterRow(_ label:String,symbol:String,value:Binding<String>,unit:String="",symbolFirst:Bool=false)->some View{ViewThatFits(in:.horizontal){HStack(spacing:10){parameterLabel(label,symbol:symbol,symbolFirst:symbolFirst);Spacer(minLength:12);parameterField(symbol,value:value,unit:unit)};VStack(alignment:.leading,spacing:5){parameterLabel(label,symbol:symbol,symbolFirst:true);parameterField(symbol,value:value,unit:unit).frame(maxWidth:.infinity,alignment:.trailing)}}}
    private func parameterLabel(_ label:String,symbol:String,symbolFirst:Bool=false)->some View{HStack(spacing:6){if symbolFirst{Text(symbol).font(.body.monospaced()).fontWeight(.semibold);Text("— \(label)").foregroundStyle(.secondary)}else{Text(label).foregroundStyle(.secondary);Text(symbol).font(.body.monospaced()).fontWeight(.semibold)}}.fixedSize(horizontal:true,vertical:true)}
    private func parameterField(_ symbol:String,value:Binding<String>,unit:String)->some View{HStack(spacing:8){TextField(symbol,text:value).multilineTextAlignment(.trailing).textFieldStyle(.roundedBorder).frame(minWidth:80,idealWidth:120,maxWidth:150);if !unit.isEmpty{Text(unit).foregroundStyle(.secondary).fixedSize()}}}
}
