import Foundation

enum MaterialPropertyKind: String, CaseIterable, Identifiable, Codable {
    case density, thermalConductivity, specificHeatCapacity, thermalExpansion, youngsModulus, poissonsRatio, yieldStrength, ultimateTensileStrength, shearModulus, compressiveStrength, electricalResistivity, smys, smts
    var id: String { rawValue }
    var name: String {
        switch self { case .density: return "Density"; case .thermalConductivity: return "Thermal conductivity"; case .specificHeatCapacity: return "Specific heat capacity"; case .thermalExpansion: return "Thermal expansion"; case .youngsModulus: return "Young's modulus"; case .poissonsRatio: return "Poisson's ratio"; case .yieldStrength: return "Yield strength"; case .ultimateTensileStrength: return "Ultimate tensile strength"; case .shearModulus: return "Shear modulus"; case .compressiveStrength: return "Compressive strength"; case .electricalResistivity: return "Electrical resistivity"; case .smys: return "SMYS"; case .smts: return "SMTS" }
    }
    var unit: String {
        switch self { case .density: return "kg/m³"; case .thermalConductivity: return "W/(m·K)"; case .specificHeatCapacity: return "J/(kg·K)"; case .thermalExpansion: return "µm/(m·K)"; case .youngsModulus, .shearModulus: return "GPa"; case .poissonsRatio: return ""; case .yieldStrength, .ultimateTensileStrength, .compressiveStrength, .smys, .smts: return "MPa"; case .electricalResistivity: return "Ω·m" }
    }
}

enum MaterialPropertyResolutionMethod: String, Codable { case constant, tableExact, linearInterpolation, equation }
enum MaterialPropertyResolutionStatus: Equatable, Codable { case resolved, missing, temperatureRequired, outsideAvailableRange(minimumC: Double, maximumC: Double), outsideEquationRange(minimumC: Double?, maximumC: Double?) }
struct MaterialPropertyResolution: Equatable, Codable { var property: MaterialPropertyKind; var value: Double?; var unit: String; var temperatureC: Double?; var method: MaterialPropertyResolutionMethod?; var status: MaterialPropertyResolutionStatus; var lowerPoint: MaterialPropertyPoint?; var upperPoint: MaterialPropertyPoint?; var source: String?; var basis: String?; var isExtrapolated: Bool; var isResolved: Bool { value != nil && status == .resolved } }

enum MaterialPropertyResolver {
    static func availableProperties(in material: EngineeringMaterial) -> [MaterialPropertyKind] { MaterialPropertyKind.allCases.filter { let d = propertyData($0, material: material); return d.scalar != nil || d.series?.referenceValue != nil || !(d.series?.temperatureTable.isEmpty ?? true) || d.series?.equation != nil } }
    static func resolve(_ property: MaterialPropertyKind, in material: EngineeringMaterial, atTemperatureC temperatureC: Double? = nil) -> MaterialPropertyResolution {
        let data = propertyData(property, material: material)
        guard let series = data.series else { guard let scalar = data.scalar else { return make(property, temperatureC, nil, nil, .missing) }; return make(property, temperatureC, scalar, .constant, .resolved, source: material.source) }
        if let equation = series.equation { guard let temperatureC else { return make(property, nil, nil, nil, .temperatureRequired, source: series.source ?? material.source, basis: series.basis) }; let outside = (equation.minimumTemperatureC.map { temperatureC < $0 } ?? false) || (equation.maximumTemperatureC.map { temperatureC > $0 } ?? false); if outside && !equation.allowsExtrapolation { return make(property, temperatureC, nil, nil, .outsideEquationRange(minimumC: equation.minimumTemperatureC, maximumC: equation.maximumTemperatureC), source: series.source ?? material.source, basis: series.basis) }; return make(property, temperatureC, equation.value(atTemperatureC: temperatureC), .equation, .resolved, source: series.source ?? material.source, basis: series.basis, extrapolated: outside) }
        let points = series.temperatureTable.sorted { $0.temperatureC < $1.temperatureC }
        if !points.isEmpty { guard let temperatureC else { if points.count == 1, let p = points.first { return make(property, p.temperatureC, p.value, .tableExact, .resolved, lower: p, upper: p, source: series.source ?? material.source, basis: series.basis) }; return make(property, nil, nil, nil, .temperatureRequired, source: series.source ?? material.source, basis: series.basis) }; let first = points[0], last = points[points.count - 1]; guard temperatureC >= first.temperatureC, temperatureC <= last.temperatureC else { return make(property, temperatureC, nil, nil, .outsideAvailableRange(minimumC: first.temperatureC, maximumC: last.temperatureC), source: series.source ?? material.source, basis: series.basis) }; if let exact = points.first(where: { $0.temperatureC == temperatureC }) { return make(property, temperatureC, exact.value, .tableExact, .resolved, lower: exact, upper: exact, source: series.source ?? material.source, basis: series.basis) }; for i in 0..<(points.count - 1) { let lo = points[i], hi = points[i + 1]; if temperatureC > lo.temperatureC && temperatureC < hi.temperatureC { let f = (temperatureC - lo.temperatureC) / (hi.temperatureC - lo.temperatureC); return make(property, temperatureC, lo.value + f * (hi.value - lo.value), .linearInterpolation, .resolved, lower: lo, upper: hi, source: series.source ?? material.source, basis: series.basis) } } }
        if let reference = series.referenceValue ?? data.scalar { return make(property, series.referenceTemperatureC ?? temperatureC, reference, .constant, .resolved, source: series.source ?? material.source, basis: series.basis) }
        return make(property, temperatureC, nil, nil, .missing, source: series.source ?? material.source, basis: series.basis)
    }
    private static func make(_ property: MaterialPropertyKind, _ temperatureC: Double?, _ value: Double?, _ method: MaterialPropertyResolutionMethod?, _ status: MaterialPropertyResolutionStatus, lower: MaterialPropertyPoint? = nil, upper: MaterialPropertyPoint? = nil, source: String? = nil, basis: String? = nil, extrapolated: Bool = false) -> MaterialPropertyResolution { MaterialPropertyResolution(property: property, value: value, unit: property.unit, temperatureC: temperatureC, method: method, status: status, lowerPoint: lower, upperPoint: upper, source: source, basis: basis, isExtrapolated: extrapolated) }
    private static func propertyData(_ kind: MaterialPropertyKind, material: EngineeringMaterial) -> (scalar: Double?, series: MaterialPropertySeries?) { switch kind { case .density: return (material.densityKgM3,nil); case .thermalConductivity: return (material.thermalConductivityWMK,material.thermalConductivitySeries); case .specificHeatCapacity: return (material.specificHeatCapacityJkgK,material.specificHeatCapacitySeries); case .thermalExpansion: return (material.thermalExpansionMicrostrainPerK,material.thermalExpansionSeries); case .youngsModulus: return (material.youngsModulusGPa,material.youngsModulusSeries); case .poissonsRatio: return (material.poissonsRatio,material.poissonsRatioSeries); case .yieldStrength: return (material.yieldStrengthMPa,material.yieldStrengthSeries); case .ultimateTensileStrength: return (material.ultimateTensileStrengthMPa,material.ultimateTensileStrengthSeries); case .shearModulus: return (material.shearModulusGPa,material.shearModulusSeries); case .compressiveStrength: return (material.compressiveStrengthMPa,nil); case .electricalResistivity: return (material.electricalResistivityOhmM,material.electricalResistivitySeries); case .smys: return (material.smysMPa,nil); case .smts: return (material.smtsMPa,nil) } }
}
